---
configure_terminal: yes
configure_osx: yes
configure_dotfiles: yes

dotfiles_repo: git@github.com:breizhspiff/dotfiles.git
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: ~/dotfiles
dotfiles_files:
  - .aliases
  - .functions
  - .gitconfig
  - .gitignore_global
  - .osx
  - .vim
  - .vimrc
  - .zshrc

homebrew_installed_packages:
  - openssl
  - git
  - tree
  - python
  - python3
  - sqlite
  - nmap
  - ssh-copy-id
  - wget
  - ethereum
  - postgresql
  - plantuml
  - node
  - maven
  - markdown
  - graphviz
  - openssl

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - homebrew/cask-drivers
  - homebrew/cask-versions

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - zoomus
  - sonos
  - docker
  - google-chrome
  - java
  - vagrant
  - virtualbox
  - vlc
  - iterm2
  - postman
  - atom
  - intellij-idea
  - betterzipql
  - qlimagesize
  - suspicious-package
  - spotify
  - evernote
  - postico
  - sequel-pro
  - skype-for-business
  - visual-studio-code
  - go2shell
  - aegisub
  - dashlane
  - adobe-acrobat-reader
  - android-file-transfer
  - atom
  - blockstack
  - brackets
  - caffeine
  - camunda-modeler
  - cyberduck
  - daedalus
  - dashlane
  - disk-inventory-x
  - divvy
  - ethereum-wallet
  - firefox
  - ganache
  - github
  - gitter
  - go2shell
  - home-inventory
  - joinme
  - libreoffice
  - makemkv
  - merlin-project
  - mist
  - omnifocus
  - omnigraffle
  - openbazaar
  - plex-media-player
  - plexamp
  - rstudio
  - skitch
  - skype
  - slack
  - teamviewer
  - tibco-jaspersoft-studio
  - transmission
  - tunnelblick
  - whatsapp
  - workplace-chat
  - nextcloud
  - paw
  - archi

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_app_ids:
  - 999177212 # UnRAR Free (1.3)
  - 526298438 # Lightshot Screenshot (2.18)
  - 1153157709 # Speedtest by Ookla (1.5)
  - 549083868 # Display Menu (2.2.3)
  - 568494494 # Pocket (1.7.8)
  - 937984704 # Amphetamine (3.0.2)
  - 865500966 # feedly. Read more, know more. (0.2)
  - 1255878751 # Visual Budget Easy (1.24)
  - 1190651975 # eidReader (1.1.2)
  - 963642514 # Duplicate Photos Fixer Pro (2.5)

#mas_email: ""
#mas_password: ""
